---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
  changed_when: false
  when: ansible_distribution == "CentOS"

#- name: Get vector distrib
#  ansible.builtin.get_url:    
#    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
#    dest: /tmp/vector.deb
#    force: yes
#  changed_when: false
#  when: ansible_distribution == "Ubuntu"

- name: Install vector CentOS
  become: yes
  become_method: su
  become_user: root
  ansible.builtin.yum:
    name: vector-{{ vector_version }}.rpm
    disable_gpg_check: yes
  changed_when: false
  when: ansible_distribution == "CentOS"
  notify: Start vector

- name: Install vector Ubuntu
  become: yes
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    force: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"
  notify: Start vector

