---
- name: Converge
  hosts: all
  pre_tasks:
   # - name: Uncomment appstream repo
     # become: yes
     # become_method: su
     # ansible.builtin.raw: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* 
   # - name: Uncomment appstream repo
     # become: yes
     # become_method: su
     # ansible.builtin.raw: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
   # - name: Update Package Cache (dnf/CentOS)
     # dnf:
       # update_cache: yes
   - name: Upgrade all packages
     yum: 
       name: "*"
       state: latest
#  - name: Install Python on Centos
#      become: yes
#      ansible.builtin.package:
#        name: python3
  tasks:
    - name: "Include vector"
      include_role:
        name: "vector"
